### ISSUE TITLE
Is it possible to name my state store when ::w/entity-type is :ktable?

### ISSUE THREAD

**Issue by cjbarre** [DaveWM/willa#15]
I couldn't figure this one out and it's not really referenced in the documentation that I could see. My use-case is establishing a ktable with the intention to query it outside of the topology as a local state store. I need a consistent name instead of a gensym for obvious reasons. I looked in the code and believe I determined that this is not supported, so I have pushed a PR for you to check out, to see if it's something you'd like to support.

#14

**Comment by DaveWM** [comment]
You're right, this wasn't supported, thanks again for your PR. I've merged it, and deployed the changes in version `0.2.0` :rocket:
