### ISSUE TITLE
No method in multimethod 'coerce-to-ktable' when building topology

### ISSUE THREAD

**Issue by pdmct** [DaveWM/willa#2]
When I try to build this topology I get a No method in multimethod 'coerce-to-ktable' for dispatch value: class jackdaw.streams.interop.CljTimeWindowedKStream exception. 

Changing the :ktable to :kstream will allow the topology to build but I think it produces different semantics of the stream.

```
(def workflow
  [[:input-topic :aggregate-stream]
   [:aggregate-stream :output-topic]])

(def entities
 {:input-topic {::w/entity-type :topic
                :topic-name "timed-readings-topic"
                :replication-factor 1
                :partition-count 1
                :key-serde (serdes.edn/serde)
                :value-serde (serdes.edn/serde)}
  :aggregate-stream {::w/entity-type :ktable
                     :willa.core/group-by-fn (fn [[k v]] (:device-number v))
                     :willa.core/window (TimeWindows/of (* 2 60 1000))} 
  :output-topic {::w/entity-type :topic
                 :topic-name "timed-readings-output-topic"
                 :replication-factor 1
                 :partition-count 1
                 :key-serde (serdes.edn/serde)
                 :value-serde (serdes.edn/serde)}})
```

**Comment by DaveWM** [comment]
@pdmct I think Willa is behaving as designed, but the readme is unclear and perhaps the API could be improved. In this example, the `input-topic` is treated as a `KStream`, which is grouped and windowed into a [TimeWindowedKStream](https://kafka.apache.org/10/javadoc/org/apache/kafka/streams/kstream/TimeWindowedKStream.html). To sink this to a topic, you also need to aggregate it, so you need to add the `:willa.core/aggregate-adder-fn` and `:willa.core/aggregate-initial-value` keys. 

What would you expect the output on `output-topic` to be in this case? Would you expect the records in each window be grouped into a vector?

**Comment by DaveWM** [comment]
I've updated the readme to make this behaviour more explicit, and I've also updated the specs in version `0.1.2`
