### ISSUE TITLE
Upgrade Willa's Jackdaw Dep to v0.8.0

### ISSUE THREAD

**Issue by cjbarre** [DaveWM/willa#21]
Something may have changed within the Kafka Streams API. Trying to bump the jackdaw version for Willa causes tests to fail because:

`java.lang.NoSuchMethodError: 'org.apache.kafka.streams.processor.internals.ProcessorTopology org.apache.kafka.streams.processor.internals.InternalTopologyBuilder.build(java.lang.Integer)`

I'm just starting to keep up with this stuff, it looks like InternalTopologyBuilder has been deprecated.

Any idea what needs to be done @DaveWM?

**Comment by DaveWM** [comment]
I think it was just that the `org.apache.kafka/kafka-streams-test-utils` test dependency needed to be bumped up to `2.8.0`. I've just pushed version `0.2.2` which uses jackdaw `0.8.0`.
