### ISSUE TITLE
Avoid viz dependency in core (HeadlessException in docker)

### ISSUE THREAD

**Issue by focusaurus** [DaveWM/willa#3]
If I load `willa.core` in a repl running in docker, I see this error:

```
Syntax error (HeadlessException) compiling at (viz.clj:27:1).

No X11 DISPLAY variable was set, but this program performed an operation which requires it.
class clojure.lang.Compiler$CompilerException
```

Could `willa.core` be restructured to not load viz or rhizome stuff?

**Comment by DaveWM** [comment]
Hi @focusaurus, thanks for raising the issue. I've removed the require for `rhizome.viz` from `willa.core`, and pushed the fix to the `0.1.1-SNAPSHOT` version. I'll release a stable version `0.1.1` at the weekend.
