### ISSUE TITLE
thoughts on kstream branch?

### ISSUE THREAD

**Issue by focusaurus** [DaveWM/willa#4]
I wanted to check in to see if you have put any thought onto how support for kstream branching via `jackdaw.streams/branch` might work. Seems like it might be representable in the willa `build-topology!` map but there's probably options there about the exact structure of the data form and how the code to build would look.

**Comment by DaveWM** [comment]
I have indeed put some thought into how branching works. I came to the conclusion that you can replicate the `jackdaw.streams/branch` functionality by "fanning out" a topic/stream to multiple streams. You can then attach transducers to each output stream to filter the input if you want. 

For example, let's say you want to branch a stream of integers into 2 streams, based on whether they're even. You'd do something like:

```clojure
(def entities
  {:input-stream {::w/entity-type :kstream}
   :branch-1 {::w/entity-type :kstream
                     ::w/xform (filter (fn [[k v]] (even? v)))}
   :branch-2 {::w/entity-type :kstream
                      ::w/xform (filter (fn [[k v]] (odd? v)))}})

(def workflow
  [[:input-stream :branch-1]
   [:input-stream :branch-2]])
```

Does that answer your question?

**Comment by focusaurus** [comment]
Yes, thanks! I'll give it a try. Do you think this warrants an example in the README? When I found no mention of "branch" anywhere I thought they might not be supported at all.
