### ISSUE TITLE
No method in multimethod 'join-entities*' for dispatch value: [:left :kstream :ktable]

### ISSUE THREAD

**Issue by bobby** [DaveWM/willa#5]
A left-join of a KStream and a KTable is legal (and in my use-cases, somewhat common) operation.  However, the experiment namespace doesn't support this case.

**Comment by DaveWM** [comment]
Hey @bobby, I've added kstream-ktable join support in Willa `0.1.1`, let me know if that solves your issue

**Comment by DaveWM** [comment]
I'll close the issue for now, if you're still having problems let me know and I'll re-open it
